// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PruebaML
{
    public partial class ML
    {
        /// <summary>
        /// model input class for ML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"gender")]
            public string Gender { get; set; }

            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"hypertension")]
            public float Hypertension { get; set; }

            [ColumnName(@"heart_disease")]
            public float Heart_disease { get; set; }

            [ColumnName(@"smoking_history")]
            public string Smoking_history { get; set; }

            [ColumnName(@"bmi")]
            public float Bmi { get; set; }

            [ColumnName(@"HbA1c_level")]
            public float HbA1c_level { get; set; }

            [ColumnName(@"blood_glucose_level")]
            public float Blood_glucose_level { get; set; }

            [ColumnName(@"diabetes")]
            public float Diabetes { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"hypertension")]
            public float Hypertension { get; set; }

            [ColumnName(@"heart_disease")]
            public float Heart_disease { get; set; }

            [ColumnName(@"smoking_history")]
            public float[] Smoking_history { get; set; }

            [ColumnName(@"bmi")]
            public float Bmi { get; set; }

            [ColumnName(@"HbA1c_level")]
            public float HbA1c_level { get; set; }

            [ColumnName(@"blood_glucose_level")]
            public float Blood_glucose_level { get; set; }

            [ColumnName(@"diabetes")]
            public float Diabetes { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}